name: Build

on: [ push, pull_request ]

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test internal
        run: go test -v ./internal/...

      - name: Test pkg
        run: go test -v ./pkg/...

  build-vue:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14' ]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: Installing node project dependencies
        working-directory: ./static/UI
        run: npm install

      - name: Building the project
        working-directory: ./static/UI
        run: npm run build

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: vue-frontend
          path: |
            static/UI/dist/
            !static/UI/node_modules/

  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build wasm
        run: GOOS=js GOARCH=wasm go build -o main.wasm wasm/*.go
      - uses: actions/upload-artifact@master
        with:
          name: go-wasm
          path: main.wasm

  build-go:
    needs: ['build-vue', 'build-wasm']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - uses: actions/download-artifact@master
        with:
          name: vue-frontend
          path: static/UI/dist

      - uses: actions/download-artifact@master
        with:
          name: go-wasm
          path: static/UI/dist

      - name: Generate
        run: go generate -v ./...

      - name: Build
        run: go build -v .
